### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by villav**
Not sure if this is a bug but to interact with other systems message to be expected to be base64.

### CODE REVIEW

**Comment by ogail** [comment]
Thanks @villav for the pull request! Have you signed CLA document?

**Comment by villav** [comment]
I don't think so. Do you have a link to it?

**Comment by villav** [comment]
CLA signed.

**Comment by azurecla** [comment]
Hi __@villav__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Pull request merged**
