### PR TITLE
Composer update

### PR DESCRIPTION
**Pull request by jeroenseegers**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jeroenseegers__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by jeroenseegers** [comment]
CLA is signed.

**Comment by adrianpietka** [comment]
@rnrneverdies or @devigned can you merge this pull request?

**Comment by devigned** [comment]
@jeroenseegers I'll follow up on the CLA and get this merged. /cc @mayurid

**Comment by mandersondesign** [comment]
Can you merge in this pull request as fast as possible?  PEAR is broken with composer now, and we are stuck and unable to deploy any changes until we get this resolved.

**Comment by Sazpaimon** [comment]
Wouldn't this cause an issue with pear/HTTP_Request2#11? The version of HTTP_Request2 in composer would pull in an incompatible version of Net_Url2

**Comment by azurecla** [comment]
Hi __@jeroenseegers__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
Thank you, @jeroenseegers!

**Comment by hootener** [comment]
This basically breaks everything associated with HTTP_Request2 for me. Here's the following error:

     Uncaught exception 'ErrorException' with message 'require_once(HTTP/Request2.php): failed to open stream: No such file or directory' in /path/to/project/vendor/microsoft/windowsazure/WindowsAzure/Common/Internal/Http/HttpClient.php:33

Thoughts?

**Comment by hootener** [comment]
Digging further, it appears the switch to composer for Azure's PEAR dependencies ends up autoloading the HTTP_Request2, et al. files which is exactly what it should do. However, this precludes the use of the ``require_once`` statements found in Request2, etc. These ``requires`` lead to the error in my previous comment. 

See: 
* https://github.com/composer/composer/issues/3340
* http://stackoverflow.com/questions/31484814/warning-require-oncenet-url2-php-failed-to-open-stream
 
and for a possible fix:
* https://github.com/pear/HTTP_Request2/commit/0b422776d1f01725a30f0f586ee73e3afb678bb8

**Comment by mandersondesign** [comment]
echoing @hootener here:

We are working on fixing this issue. We've forked pear/HTTP_Request2 and are adjusting it so that it will work with azure and our forked version of the azure-sdk-for-php repo. Will update when ready.

**Comment by devigned** [comment]
@mandersondesign awesome! I'll keep an eye out for the pr and get it pulled in.

**Comment by hootener** [comment]
@devigned it's hardly a PR, primarily because it impacts two codebases (i.e., azure and pear/http_request2) simultaneously. 

The revisions to the Azure SDK are actually pretty minimal, and just focus around optional requires of HTTP_Request2 to accommodate composer. 

For anyone reading this, here's a fix you can incorporate while this mess gets sorted out by either Azure, PEAR, or someone else. In the composer.json of your project, add the following to ```repositories```:

     {
      "type" : "vcs",
      "url": "https://github.com/GameWisp/azure-sdk-for-php.git"
    },
    {
      "type" : "vcs",
      "url": "https://github.com/GameWisp/HTTP_Request2.git"
    }

This will use some Repos where we've basically patched in composer-friendliness in both the Azure SDK and HTTP_Request2. I could likely put in a more robust fix for the Azure SDK as a PR, but this problem has already put me 36 hours behind on a code deployment and I *really* need to move on. 

To anyone that uses these two repos: they will not be updated by us to track changes to either the azure sdk or http_request2. I recommend using these repos like we are, as stopgaps until Azure either removes / fixes the PEAR dependency, HTTP_Request2 merges in a fix to be composer friendly, or some mixture of both.

**Comment by Sazpaimon** [comment]
I made #764 which should prevent the need for any custom repo shenanigans.

**Comment by hootener** [comment]
@Sazpaimon Where were you 30 minutes ago, friend? Seriously, though, thanks for putting together a PR that potentially puts an end to this mess.

**Pull request merged**
