### PR TITLE
Add dev requirement for `phpunit/phpunit:^4.7`

### PR DESCRIPTION
**Pull request by phansys**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

Add dev requirement for `phpunit/phpunit:^4.7` since this is the unit test framework
used by this project.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@phansys__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by yaqiyang** [comment]
This change has been merged in

**Comment by phansys** [comment]
@yaqiyang, in a community driven project is better to ask the PR author to execute `git rebase` instead of replicate the work on another PR/commit when there are some conflicts.
BTW, thank you.
Regards.

**Comment by phansys** [comment]
Merged in #785.

**Comment by yaqiyang** [comment]
@phansys, thanks a lot!. I merged it, so your contribution is still seen in the history of this commit. I will definitely ask the contributors to rebase the next time around. 

Yaqi

**Pull request closed without merging**
