### PR TITLE
Add support to SAS authorization

### PR DESCRIPTION
**Pull request by Shaked**
This pull request adds support using SAS authorization. 

As mentioned in https://github.com/Azure/azure-sdk-for-php/issues/726#issuecomment-334990993 I haven't followed the contribution guidelines but am opening a pull request in case someone wants to help with that. 

As far as I understand, Wrap authentication is deprecated so I haven't put effort in changing it to show more correct error messages (for example, I could have split `ServiceBusSettings.php` so that it will throw the correct error when using the wrong connectionString keys. 

Shaked

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@Shaked thank you for the PR.

**Comment by Shaked** [comment]
@sergey-shandar np. It should be quite easy to support php5.6 and 7.0. 

FYI php5.6 is not supported anymore: http://php.net/supported-versions.php (only security updates)

**Comment by sergey-shandar** [comment]
@Shaked yes, I've seen the table. According to this table, we may consider to drop 5.6 in 2019 :-)

**Comment by sergey-shandar** [comment]
Closed as a duplicate of https://github.com/Azure/azure-sdk-for-php/pull/958

**Pull request closed without merging**
