### PR TITLE
Updated the class registration files for sdk source and tests.

### PR DESCRIPTION
**Pull request by yaqiyang**
Updated the class registration files for sdk source and tests.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yaqiyang__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (yaya). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by phansys** [comment]
@yaqiyang, I don't understand which is the reason to register your own class loader. It's already provided by Composer.

**Comment by yaqiyang** [comment]
@phansys , I just removed the reference to them from the examples. But maybe some users are still using them and want them to be updated to reflect the current state.  New users will definitely not need them anymore. 

Thanks
Yaqi

**Comment by phansys** [comment]
I think it should be completely removed, users who relies in this feature should keep using the previous versions of this library. So, if you consider removing this a BC break, `master` should point to a branch alias `1.0` in order to respect [semantic versioning](http://semver.org/).

**Comment by yaqiyang** [comment]
That sounds good. I will move these two files to the deprecated folder and then plan to remove all files there after this release. 

Thanks
Yaqi

**Comment by phansys** [comment]
@yaqiyang, IMHO, there is no sense in moving code to another location when the purpose is mark something as deprecated. If any part of the application is being deprecated, it should be documented with the corresponding `@deprecated` docblock, indicating in which version it will be removed and if there is any replacement for that. In the same way, a call to `trigger_error()` alongside `E_USER_DEPRECATED` must be triggered, in order to allow users of this library to prepare the upgrade path to the new version in an easy way.

**Comment by yaqiyang** [comment]
@phansys, please take a look at PR 803. I have add the @deprecated dock block.

Thanks for your contributions.
Yaqi Yang

**Comment by phansys** [comment]
You're welcome @yaqiyang.
I've left some comments.

**Pull request closed without merging**
