### PR TITLE
Adopt PSR-2 as basic CS + add requirement for `php-cs-fixer`

### PR DESCRIPTION
**Pull request by phansys**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #793
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@phansys__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by yaqiyang** [comment]
@phansys , can you clean up the changes for the current code base?

Thanks
yaqi

**Comment by phansys** [comment]
I've applied the rebase in 2 separated commits (one for the dependency addition and another for the fixes). Please let me know if both of them are good in order to squash.

**Comment by yaqiyang** [comment]
Thanks. What is the command to check for compliance after a code change?

**Comment by phansys** [comment]
I've asked you to tell me if it was right before merging in order to squash the commits @yaqiyang; otherwise the commit history becomes untidy. I've opened an issue for this topic some time ago: #771.
Answering your question, if you only want to check if the code respect the configured rules, you must run `./vendor/bin/php-cs-fixer --dry-run --diff`. Note that without the `--dry-run` option, the command will update the files fixing the offending rules.

**Comment by yaqiyang** [comment]
I squash-merged. Is that not right?

**Comment by phansys** [comment]
Sorry @yaqiyang, that's right. I didn't noticed that. Thank you.

**Pull request merged**
