### PR TITLE
Use Zend-Mime instead of PEAR package. PHP 7.

### PR DESCRIPTION
**Pull request by sergey-shandar**

### CODE REVIEW

**Comment by sergey-shandar** [comment]
#797 and #878.

**Comment by mconverti** [comment]
@sergey-shandar quick questions: after applying these updates/changes, have you manually verified that:
- the Media Services functional tests are all still running OK? [https://github.com/Azure/azure-sdk-for-php/tree/master/tests/unit/WindowsAzure/MediaServices](https://github.com/Azure/azure-sdk-for-php/tree/master/tests/unit/WindowsAzure/MediaServices)
- the Media Services samples are all still running OK? [https://github.com/Azure/azure-sdk-for-php/tree/master/examples/MediaServices](https://github.com/Azure/azure-sdk-for-php/tree/master/examples/MediaServices)

Thanks,
Mariano

**Comment by sergey-shandar** [comment]
@mconverti functional tests are good. I haven't tested samples. I will do it today.

**Comment by mconverti** [comment]
@sergey-shandar great! :)

By default, the samples are configured to use the published composer package, so please load your updated local version of the SDK files.

I think you just need to change the path to the autoload.php file.

 ```PHP
require_once __DIR__.'/../../vendor/autoload.php';
 ```

Thanks!
Mariano

**Comment by sergey-shandar** [comment]
All these samples are ok:

- examples/MediaServices/analyticsworkflow_indexer.php
- examples/MediaServices/liveworkflow_features.php
- examples/MediaServices/scale_encoding_units.php
- examples/MediaServices/vodworkflow_aes.php
- examples/MediaServices/vodworkflow_drm_playready_widevine.php

I haven't run this one since it requires to setup FairPlay:
- examples/MediaServices/vodworkflow_drm_fairplay.php

**Pull request merged**
