### PR TITLE
Allow firebase/jwt to be installed in version 5.0 and above

### PR DESCRIPTION
**Pull request by svengerlach**
[firebase/jwt](https://github.com/firebase/php-jwt)'s versioning scheme isn't ideal. However, version 5.0.0 bas been released on 2017-06-27. I've updated the composer.json to allow version 5.0.0 (and above) or version 4.0.0 (and above). Version requirement '^4.0' made it impossible to install the Azure SDK for PHP in projects that already required firebase/jwt in version '^>=5.0' in their own composer.json.

### CODE REVIEW

**Comment by svengerlach** [comment]
Hey @sergey-shandar - thanks for the merge. Could you tag that commit as a new release (e.g. 0.5.8)?

Additionally, #953 could be closed as in that issue the author asks for an update to firebase-jwt >= 5.0.

**Comment by andrews05** [comment]
@sergey-shandar As above, please publish a new release. This was merged over 2 years ago but without tagging a new release I still can't install due to composer dependancy conflicts.

**Comment by williamyiu** [comment]
Is there a new release for this?

**Comment by StyxOfDynamite** [comment]
There doesn't seem to be a release available on packagist for this yet?

**Comment by andrews05** [comment]
@vinjiang: Pinging another Azure PHP developer - this package doesn't seem to be maintained anymore, do you know what the status is?

**Pull request merged**
