### PR TITLE
Add platform requirement to `php: ^5.4`. This sets the supported PHP versions as 5.4 and up but not 7.x which has problems with composer.phar

### PR DESCRIPTION
**Pull request by phansys**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

Add platform requirement to `php: ^5.4` since there are usages of short array
syntax (which only works in PHP +5.4: http://docs.php.net/manual/en/language.types.array.php)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@phansys__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by konstantin-komelin** [comment]
Provided the pull request to fix some of the compatibility issues https://github.com/Azure/azure-sdk-for-php/pull/780 As I see, the short array syntax is the only problem. Can you use the long form instead? Not a big difference from my point of view.

**Comment by devigned** [comment]
Thank you for the contribution. It's assigned and will be reviewed shortly.

**Comment by phansys** [comment]
Thanks @devigned.

**Comment by devigned** [comment]
@phansys my pleasure. We're going to be giving this project more attention going forward. I'm sorry for the delay on this contribution. I assure you it will not be that way moving forward. If you need some attention please just ping me, @yaqiyang or @YuvalMazor. We're here to make this a better experience. Cheers!

**Comment by phansys** [comment]
Thanks @yaqiyang.

**Comment by Sazpaimon** [comment]
@phansys Can you elaborate what issues you have with PHP 7? I'm using PHP 7 with composer and the Azure SDK with no issues.

**Comment by phansys** [comment]
@Sazpaimon, I haven't any issue with this library and PHP 7.0 because I have no work yet on that combination.
I think you believe that I have issues because the [title update](https://github.com/Azure/azure-sdk-for-php/pull/768#event-590995702) done by @yaqiyang.
Please, ask him about this situation.
Thank you.

**Comment by Sazpaimon** [comment]
Unfortunately with this PR, the SDK cannot be installed on PHP 7 on composer without `--ignore-platform-reqs`. It might be a better idea to do `>=5.4` instead of `^5.4`

**Comment by phansys** [comment]
@Sazpaimon, if it supports `php 7.0` the constraint should be updated to something like `"php": "^5.4 || ^7.0"`.
If that assert is true, I can create a PR proposing this change.

**Comment by Sazpaimon** [comment]
I've only been using the SDK on PHP 7 for retrieving blobs from blob storage, but I haven't run into any issues with that.

**Comment by yaqiyang** [comment]
Thanks a lot for all the replies. I am in the process of testing for PHP 7.0 and will change the requirement to 5.4 and up including PHP 7.0 once all tests pass.

Thanks again
Yaqi Yang

**Comment by phansys** [comment]
@yaqiyang, regarding the tests, is there any CI suite where you're running the project?
I've proposed Travis CI in #773.

**Comment by yaqiyang** [comment]
I am hitting this issue https://bugs.php.net/bug.php?id=71317 with PHP 7. Just tried 7.0.4 and the problem is still there.

What build of PHP 7 are you using and on what OS?

Thanks
Yaqi

**Comment by Sazpaimon** [comment]
I ran into this issue when using the pear packages from the pear repo, but since master now gets the pear packages from packagist, they don't need to unpack the tarballs anymore.

**Comment by Sazpaimon** [comment]
```
$ php --version
PHP 7.0.4 (cli) (built: Mar 10 2016 23:51:04) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
$ composer require microsoft/windowsazure:dev-master --ignore-platform-reqs
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing pear/net_url2 (v2.1.1)
    Loading from cache

  - Installing pear/pear_exception (v1.0.0)
    Loading from cache

  - Installing pear/mail_mime-decode (1.5.5.2)
    Loading from cache

  - Installing pear/console_getopt (v1.4.1)
    Loading from cache

  - Installing pear/pear-core-minimal (v1.10.1)
    Loading from cache

  - Installing pear/mail_mime (1.10.0)
    Loading from cache

  - Installing pear/http_request2 (v2.2.1)
    Loading from cache

  - Installing firebase/php-jwt (v3.0.0)
    Loading from cache

  - Installing microsoft/windowsazure (dev-master 9c66662)
    Cloning 9c6666261647b82208e7feb86a4d3a0b02b693dc

Writing lock file
Generating autoload files
```

**Pull request merged**
