### PR TITLE
Remove `build` dir + add requirements for dev tools

### PR DESCRIPTION
**Pull request by phansys**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | #813
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@phansys__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by yaqiyang** [comment]
Why do you want to move phpcs.xml and phpmd.xml to the root? They are being referenced by build.xml. is the build folder not right for them?

**Comment by yaqiyang** [comment]
Also, the new dev packages will bring in a LOT of new packages. I need to know what exactly we benefit from the new entries in the composer.json file. 

Thanks
yaqi

**Comment by phansys** [comment]
These files as any other configuration files for 3rd party tools are used to be placed at project's root directory. Obviously, they can be placed in any dir, but it's a wide common practice to put them at the root (just like [phpdoc.dist.xml](https://github.com/Azure/azure-sdk-for-php/blob/66623ce12bb27e70d131533572954646540ab2ee/phpdoc.dist.xml) and [phpunit.xml.dist](https://github.com/Azure/azure-sdk-for-php/blob/6e879be02a50d1326ee61f9c8f1b5031a39cd0dc/phpunit.xml.dist)).

**Comment by phansys** [comment]
@yaqiyang, these tools are required to execute the checks that are defined in at `phpcs.xml` and `phpmd.xml`. Obviously, each dependency can have many other dependencies: this is the main principle behind dependency management.
IMO, the benefit of adding them as DEV dependencies it to have a fully functional DEV environment with all the dependencies of this project defined within the package. Otherwise, how is supposed to execute the rules defined at these config files (which are already part of this library)?
Please, note that DEV dependencies are only installed when you are using this library in a standalone way (mainly this situation only happen when you're developing on this, such fixing a bug or creating a new feature). Users which have this library as a dependency will not get all of the packages defined in the `require-dev` directive.

**Comment by phansys** [comment]
I've moved `build/relase_tools.php` to `bin/release-tool` and added shebang to this script, since it is intended to run from CLI.
About DEV dependencies, reading `build.xml` I've found many others, like "PHP Depend", "PHP CodeBrowser", "PHP Copy/Paste Detector" and "PHPLOC".

**Comment by phansys** [comment]
Added missing DEV dependencies.

**Comment by yaqiyang** [comment]
@phansys , can you clean up this PR? We will re-evaluate it for the May release.

Thanks
Yaqi

**Comment by phansys** [comment]
Done @yaqiyang.

**Comment by yaqiyang** [comment]
@phansys , I may not have enough time to evaluate this PR and put it in the May release. But I promise I will take a close look at it a bit later. 
Thanks a lot for your contribution!
Yaqi

**Comment by phansys** [comment]
There is no hurry for me at this PR since I expect these checks will be executed by the CI suite. So I must wait for that too.
Thank you so much for the advice.

**Comment by yaqiyang** [comment]
Here is my plan
1. I plan to merge this PR in after the May release is out
2. Leave release_tools.php in the build folder (somehow your version of this file is out of date). Or just rename build folder to "bin" and update references in other files for it. No need to remove the .php extension from the file name.
3. Rename WindowsAzure folder to src as you did before and update references, if any

Thanks a lot for your contribution!

Yaqi

**Comment by phansys** [comment]
Fine @yaqiyang, let me do the required updates. I'll ping you when I have all of them addressed.

**Comment by phansys** [comment]
Done. Please let me know if any other change is required.

**Pull request merged**
